import { createApp } from "vue";
import "./style.css";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import Toast from "vue-toastification";
import "vue-toastification/dist/index.css";
import App from "./App.vue";
const app = createApp(App);
const toastOptions = {};
app.use(ElementPlus);
app.use(Toast, toastOptions);
app.mount("#app");
